<?php

/**
 * HELP jintekikojo本文辞書（このページ専用）
 * key はボタンの data-help-key と一致させる
 */


return [
   'kafu_hitorioya' => [
    'title' => '寡婦控除・ひとり親控除',
    'html'  => ''
        . '<div class="help-text">　以下の控除額は全て所得税に関するものです。住民税については「所得税と住民税の人的控除額の比較」をご覧下さい。</div>'
        . '<div class="help-text">　納税者が<span style="color:#701616;">寡婦</span>（★）であるときは、27万円を寡婦控除として所得金額から控除できます。<br>'
        . '　また、納税者が<span style="color:#701616">ひとり親</span>（★）であるときは、35万円をひとり親控除として所得金額から控除できます。</div>'
        . '<div class="help-text" style="padding-left:2.5em; text-indent:-2.5em;">★<span style="color:#701616">寡婦</span><br>原則としてその年の12月31日の現況で、本人の合計所得金額が500万円以下で、次の<span style="color:#701616;">いずれかに</span>当てはまる人（ひとり親に該当する人を除く）です（事実上婚姻関係と同様の事情にあると認められる場合を除く）。<br>'
        . '　① 夫と死別した後、婚姻をしていない人または夫の生死が明らかでない人<br>'
        . '　② 夫と離婚した後、婚姻をしておらず扶養親族がいる人</div>'
        . '<div class="help-text" style="padding-left:2.5em; text-indent:-2.5em;">★<span style="color:#701616">ひとり親</span><br>原則としてその年の12月31日の現況で、次の<span style="color:#701616;">全てに</span>当てはまる人。<br>'
        . '　① 本人の合計所得金額が500万円以下<br>'
        . '　② 婚姻をしていないこと、または配偶者の生死の明らかでない人<br>'
        . '　② 生計を一にする子（その年分の総所得金額等が58万円以下で、他の人の同一生計配偶者や扶養親族になっていない）がいる人（事実上婚姻関係と同様の事情にあると認められる場合を除く）。</div>'
        . '<div class="help-text">　具体的には次の「寡婦控除・ひとり親控除の判定」で行います。より詳しくは令和２年５月に国税庁が公表した「ひとり親控除及び寡婦控除に関するＦＡＱ」を参照して下さい。</div>'
        . '<div><strong>○寡婦控除・ひとり親控除の判定</strong></div>'
       . '<table class="help-tax-table mx-auto" style="width:660px;">'
        . '  <thead>'
        . '    <tr>'
        . '      <th colspan="6">寡婦控除・ひとり親控除の判定</th>'
        . '      <th>控除区分</th>'
        . '      <th>控除額</th>'
        . '    </tr>'
        . '  </thead>'
        . '  <tbody>'
        . '    <tr>'
        . '      <th rowspan="10" style="width:100px;">本人の合計<br>所得金額が<br>500万円以下</th>'
        . '      <th rowspan="9" style="width:80px;">婚姻なし<br>（※３）</th>'
        . '      <th rowspan="2" colspan="2">男性</th>'
        . '      <td colspan="2" class="text-start nowrap">扶養する子あり（※２）</td>'
        . '      <td style="width:110px;">ひとり親控除</td>'
        . '      <td style="width:80px;">35万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td colspan="2" class="text-start nowrap">扶養する子なし</td>'
        . '      <td>非該当</td>'
        . '      <td>－</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <th rowspan="7" style="width:44px;">女性</th>'
        . '      <th rowspan="2" style="width:46px;">死別<br>（※１）</th>'
        . '      <td colspan="2" class="text-start nowrap">扶養する子あり（※２）</td>'
        . '      <td>ひとり親控除</td>'
        . '      <td>35万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td colspan="2" class="text-start nowrap">扶養する子なし</td>'
        . '      <td>寡婦控除</td>'
        . '      <td>27万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <th rowspan="3">離婚</th>'
        . '      <td colspan="2" class="text-start nowrap">扶養する子あり（※２）</td>'
        . '      <td>ひとり親控除</td>'
        . '      <td>35万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td rowspan="2" class="text-start nowrap" style="width:100px;">扶養する子なし</td>'
        . '      <td class="text-start nowrap" style="width:100px;">扶養親族あり</td>'
        . '      <td>寡婦控除</td>'
        . '      <td>27万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap">扶養親族なし</td>'
        . '      <td>非該当</td>'
        . '      <td>－</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <th rowspan="2">未婚</th>'
        . '      <td colspan="2" class="text-start nowrap">扶養する子あり（※２）</td>'
        . '      <td>ひとり親控除</td>'
        . '      <td>35万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td colspan="2" class="text-start nowrap">扶養する子なし</td>'
        . '      <td rowspan="3">非該当</td>'
        . '      <td rowspan="3">－</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <th colspan="5" class="text-start">婚姻あり</th>'      
        . '    </tr>'
        . '    <tr>'
        . '      <th colspan="6" class="text-start">上記以外</th>'     
        . '    </tr>'
        . '  </tbody>'
        . '</table>'
        . '<div class="help-text" style="padding-left:2.6em; text-indent:-2.6em; line-height:1.3; margin-bottom:0;">※１：生死不明を含む。</div>'
        . '<div class="help-text" style="padding-left:2.6em; text-indent:-2.6em; line-height:1.3; margin-bottom:0;">※２：総所得金額等が58万円以下の生計を一にする子であること。なお、扶養親族には事業専従者は含まれないが、上記の生計を一にする子には事業専従者である場合を含む。</div>'
        . '<div class="help-text" style="padding-left:2.6em; text-indent:-2.6em; line-height:1.3;">※３：婚姻には再婚、事実婚を含む。</div>',
    ],

    'kinrogakusei' => [
        'title' => '勤労学生控除',
        'html'  => ''
        . '<div class="help-text">　納税者がその年の12月31日の現況で、<span style="color:#701616;">勤労学生</span>（★）であるときは、27万円を勤労学生控除として所得金額から控除できます。</div>'
        . '<div class="help-text">★<span style="color:#701616;">勤労学生</span><br>'
        . '　　①合計所得金額が85万円（給与収入で150万円）以下<br>'
        . '　　②勤労によらない所得が10万円以下<br>'
        . '　　③<span style="color:#701616;">特定の学校</span>（★）の学生や生徒<br>'
        . '　　である者をいう。</div>'
        . '<div class="help-text" style="padding-left:2.5em; text-indent:-2.5em; margin-bottom:4px;">★<span style="color:#701616;">特定の学校</span></div>'
        . '<div class="help-text" style="padding-left:2em; text-indent:-0.5em; line-height:1.35; margin-bottom:0;">・学校教育法に規定する小学校、中学校、高等学校、大学（大学院を含む）、高等専門学校など</div>'
        . '<div class="help-text" style="padding-left:2em; text-indent:-0.5em; line-height:1.35; margin-bottom:0;">・国、地方公共団体、学校法人等により設置された専修学校等のうち一定の要件に当てはまる過程を履修させるもの</div>'
        . '<div class="help-text" style="padding-left:2em; text-indent:-0.5em; line-height:1.35;">・認定教育訓練を行う職業訓練法人等で一定の要件に当てはまる過程を履修させるもの</div>',
       
    ],

    'shogaisha' => [
        'title' => '障害者控除',
      'html'  => ''
        . '<div class="help-text">　納税者自身または同一生計配偶者および扶養親族がその年の12月31日の現況で障害者である場合には、障害者控除として障害者1人につき27万円を所得金額から控除できます(特別障害者の場合は40万円、同居特別障害者の場合は75万円)。</div>'
        . '<div class="help-text">　ここでは障害者控除に関しては結論部分しか書いていませんが、様々な要件がありますので適用に当たってはネット等で確認するようにして下さい。</div>'
    ],

'haigusha' => [
    'title' => '配偶者控除',
    'html'  => ''
        . '<div class="help-text">　納税者に<span style="color:#701616;">控除対象配偶者</span>（★）がいる場合には、配偶者控除として一定の金額を所得金額から控除できます。</div>'

        . '<div class="help-text" style="padding-left:2.5em; text-indent:-2.5em; margin-bottom:4px;">★<span style="color:#701616;">控除対象配偶者</span></div>'
        . '<div class="help-text" style="padding-left:2.5em;">納税者本人の合計所得金額が1,000万円以下である場合の「<span style="color:#701616;">同一生計配偶者</span>（★）」をいう。</div>'

        . '<div class="help-text" style="padding-left:2.5em; text-indent:-2.5em; margin-bottom:4px;">★<span style="color:#701616;">同一生計配偶者</span></div>'
        . '<div class="help-text" style="padding-left:2.5em; margin-bottom:4px;">その年の12月31日の現況で、次の<span style="color:#701616;">全ての</span>要件に当てはまる人をいう。</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">①民法の規定による配偶者であること（内縁関係の人は該当しない）</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">②納税者と生計を一にしていること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">③合計所得金額が58万円（給与収入で123万円）以下であること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">④青色申告者の青色事業専従者または白色申告者の事業専従者でないこと</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25;">⑤他の人の扶養親族となっていないこと</div>'

        . '<div style="padding-left:4em;"><strong>○配偶者控除の金額</strong></div>'
        . '<table class="help-tax-table mx-auto" style="width:340px;">'
        . '  <thead>'
        . '    <tr>'
        . '      <th rowspan="2" style="width:180px;">納税者の合計所得金額</th>'
        . '      <th colspan="2">配偶者控除の金額</th>'
        . '    </tr>'
        . '    <tr>'
        . '      <th style="width:80px; background:#F7F9FB;">一般</th>'
        . '      <th style="width:80px; background:#F7F9FB;">老人</th>'
        . '    </tr>'
        . '  </thead>'
        . '  <tbody>'
        . '    <tr>'
        . '      <td class="text-start nowrap">900万円以下</td>'
        . '      <td class="text-center nowrap">38万円</td>'
        . '      <td class="text-center nowrap">48万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap">900万円超　950万円以下</td>'
        . '      <td class="text-center nowrap">26万円</td>'
        . '      <td class="text-center nowrap">32万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap">950万円超　1,000万円以下</td>'
        . '      <td class="text-center nowrap">13万円</td>'
        . '      <td class="text-center nowrap">16万円</td>'
        . '    </tr>'
        . '  </tbody>'
        . '</table>'

        . '<div class="help-text" style="padding-left:4em;">※「老人（控除対象配偶者）」とは、12月31日現在で70歳以上の人です。</div>',
],
    
'haigusha_tokubetsu' => [
    'title' => '配偶者特別控除',
    'html'  => ''
        . '<div class="help-text">　納税者に<span style="color:#701616;">控除対象配偶者</span>（★）がいる場合には、配偶者特別控除として一定の金額を所得金額から控除できます。</div>'

        . '<div class="help-text" style="padding-left:2.5em; text-indent:-2.5em; margin-bottom:4px;">★<span style="color:#701616;">控除対象配偶者</span></div>'
        . '<div class="help-text" style="padding-left:2em;">納税者本人の合計所得金額が1,000万円以下である場合の「<span style="color:#701616;">同一生計配偶者</span>（★）」をいう。</div>'

        . '<div class="help-text" style="padding-left:2.5em; text-indent:-2.5em; margin-bottom:4px;">★<span style="color:#701616;">同一生計配偶者</span></div>'
        . '<div class="help-text" style="padding-left:2.5em; margin-bottom:4px;">その年の12月31日の現況で、次の<span style="color:#701616;">全て</span>の要件に当てはまる人をいう。</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1em; line-height:1.25; margin-bottom:0;">①民法の規定による配偶者であること（内縁関係の人は該当しない）</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1em; line-height:1.25; margin-bottom:0;">②納税者と生計を一にしていること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1em; line-height:1.25; margin-bottom:0;">③合計所得金額が58万円超133万円以下（給与収入で123万円超201.6万円未満）であること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1em; line-height:1.25; margin-bottom:0;">④青色申告者の青色事業専従者または白色申告者の事業専従者でないこと</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1em;">⑤他の人の扶養親族となっていないこと</div>'

        . '<div style="padding-left:2em;"><strong>○配偶者特別控除の金額</strong></div>'
        . '<table class="help-tax-table mx-auto" style="width:460px;">'
        . '  <thead>'
        . '    <tr>'
        . '      <th colspan="2" rowspan="2">配偶者の合計所得金額</th>'
        . '      <th colspan="3">納税者の合計所得金額</th>'
        . '    </tr>'
        . '    <tr>'
        . '      <th style="background:#F7F9FB;width:100px;">900万円以下</th>'
        . '      <th style="background:#F7F9FB;width:100px;">900万円超<br>950万円以下</th>'
        . '      <th style="background:#F7F9FB;width:100px;">950万円超<br>1,000万円以下</th>'
        . '    </tr>'
        . '  </thead>'
        . '  <tbody>'
        . '    <tr>'
        . '      <td class="text-start nowrap b-r-no" style="width:80px;">58万円超</td>'
        . '      <td class="text-end nowrap b-l-no" style="width:80px;">95万円以下</td>'
        . '      <td class="text-center nowrap">38万円</td>'
        . '      <td class="text-center nowrap">26万円</td>'
        . '      <td class="text-center nowrap">13万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap b-r-no">95万円超</td>'
        . '      <td class="text-end nowrap b-l-no">100万円以下</td>'
        . '      <td class="text-center nowrap">36万円</td>'
        . '      <td class="text-center nowrap">24万円</td>'
        . '      <td class="text-center nowrap">12万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap b-r-no">100万円超</td>'
        . '      <td class="text-end nowrap b-l-no">105万円以下</td>'
        . '      <td class="text-center nowrap">31万円</td>'
        . '      <td class="text-center nowrap">21万円</td>'
        . '      <td class="text-center nowrap">11万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap b-r-no">105万円超</td>'
        . '      <td class="text-end nowrap b-l-no">110万円以下</td>'
        . '      <td class="text-center nowrap">26万円</td>'
        . '      <td class="text-center nowrap">18万円</td>'
        . '      <td class="text-center nowrap">9万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap b-r-no">110万円超</td>'
        . '      <td class="text-end nowrap b-l-no">115万円以下</td>'
        . '      <td class="text-center nowrap">21万円</td>'
        . '      <td class="text-center nowrap">14万円</td>'
        . '      <td class="text-center nowrap">7万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap b-r-no">115万円超</td>'
        . '      <td class="text-end nowrap b-l-no">120万円以下</td>'
        . '      <td class="text-center nowrap">16万円</td>'
        . '      <td class="text-center nowrap">11万円</td>'
        . '      <td class="text-center nowrap">6万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap b-r-no">120万円超</td>'
        . '      <td class="text-end nowrap b-l-no">125万円以下</td>'
        . '      <td class="text-center nowrap">11万円</td>'
        . '      <td class="text-center nowrap">8万円</td>'
        . '      <td class="text-center nowrap">4万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap b-r-no">125万円超</td>'
        . '      <td class="text-end nowrap b-l-no">130万円以下</td>'
        . '      <td class="text-center nowrap">6万円</td>'
        . '      <td class="text-center nowrap">4万円</td>'
        . '      <td class="text-center nowrap">2万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap b-r-no">130万円超</td>'
        . '      <td class="text-end nowrap b-l-no">133万円以下</td>'
        . '      <td class="text-center nowrap">3万円</td>'
        . '      <td class="text-center nowrap">2万円</td>'
        . '      <td class="text-center nowrap">1万円</td>'
        . '    </tr>'
        . '  </tbody>'
        . '</table>',
],    
    
'fuyo' => [
    'title' => '扶養控除',
    'html'  => ''
        . '<div class="help-text">　納税者に<span style="color:#701616;">控除対象扶養親族</span>（★）がいる場合には、扶養控除として一定の金額を所得金額から控除できます。</div>'

        . '<div class="help-text" style="padding-left:2.5em; text-indent:-2.5em; margin-bottom:4px;">★<span style="color:#701616;">控除対象扶養親族</span></div>'
        . '<div class="help-text" style="padding-left:2.5em; margin-bottom:4px;">その年の12月31日の現況で、次の全ての要件に当てはまる人をいう。</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">①年齢が16歳以上であること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">②配偶者以外の親族（6親等内の血族および3親等内の姻族）であること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">③納税者と生計を一にしていること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">④合計所得金額が58万円（給与収入で123万円）以下であること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">⑤青色申告者の青色事業専従者または白色申告者の事業専従者でないこと</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em;">⑥他の人の同一生計配偶者や扶養親族となっていないこと</div>'

        . '<div class="ms-4 mb-1"><strong>○親族に関連する各種名称の定義</strong></div>'
        . '<div style="display:flex; justify-content:center; align-items:flex-start; gap:0; margin:0 0 12px 0;">'


        . '  <table class="help-tax-table" style="width:auto; margin:0; table-layout:fixed;">'
        . '    <colgroup>'
        . '      <col style="width:44px;">'
        . '      <col style="width:44px;">'
        . '      <col style="width:44px;">'
        . '      <col style="width:44px;">'
        . '      <col style="width:44px;">'
        . '    </colgroup>'
        . '    <thead>'
        . '      <tr style="height:34px;">'
        . '        <th colspan="5" style="background:#e9eff7;">区　分</th>'
        . '      </tr>'
        . '    </thead>'
        . '    <tbody>'
        . '      <tr style="height:34px;">'
        . '        <th colspan="5" class="b-b-no" style="background:#F7F9FB; text-align:left;">親族</th>'
        . '      </tr>'

        . '      <tr style="height:34px;">'
        . '        <td rowspan="8" class="b-t-no" style="background:#F7F9FB;"></td>'
        . '        <th rowspan="4" colspan="4" class="b-b-no" style="background:#F7F9FB; white-space:nowrap;">扶養親族</th>'
        . '      </tr>'
        . '      <tr style="height:34px;"></tr>'
        . '      <tr style="height:34px;"></tr>'
        . '      <tr style="height:34px;"></tr>'

        . '      <tr style="height:34px;">'
        . '        <td rowspan="4" class="b-t-no" style="background:#F7F9FB;"></td>'
        . '        <th colspan="3" class="b-b-no" style="background:#F7F9FB; white-space:nowrap;">控除対象扶養親族</th>'
        . '      </tr>'

        . '      <tr style="height:34px;">'
        . '        <td rowspan="3" class="b-t-no" style="background:#F7F9FB;"></td>'
        . '        <th colspan="2" style="background:#F7F9FB; white-space:nowrap;">特定扶養親族</th>'
        . '      </tr>'

        . '      <tr style="height:34px;">'
        . '        <th colspan="2" class="b-b-no" style="background:#F7F9FB; white-space:nowrap;">老人扶養親族</th>'
        . '      </tr>'

        . '      <tr style="height:34px;">'
        . '        <td class="b-t-no" style="background:#F7F9FB;"></td>'
        . '        <th style="background:#F7F9FB; white-space:nowrap;">同居老親等（※）</th>'
        . '      </tr>'
        . '    </tbody>'
        . '  </table>'
        . '  <table class="help-tax-table" style="width:auto; margin:0 0 0 -1px;">'
        . '    <thead>'
        . '      <tr style="height:34px;">'
        . '        <th style="background:#e9eff7;">定義要件</th>'
        . '        <th style="background:#e9eff7;">控除額</th>'
        . '      </tr>'
        . '    </thead>'
        . '    <tbody>'
        . '      <tr style="height:34px;">'
        . '        <td class="text-start nowrap" style="background:#fff;">①　民法上の親族（配偶者を除く）</td>'
        . '        <td style="background:#fff;">－</td>'
        . '      </tr>'
        . '      <tr style="height:34px;">'
        . '        <td class="text-start nowrap" style="background:#fff;">②　納税者と生計を一にしている</td>'
        . '        <td rowspan="4" style="background:#fff;">－</td>'
        . '      </tr>'
        . '      <tr style="height:34px;">'
        . '        <td class="text-start nowrap" style="background:#fff;">③　合計所得金額が58万円以下</td>'
        . '      </tr>'
        . '      <tr style="height:34px;">'
        . '        <td class="text-start nowrap" style="background:#fff;">④　青色事業専従者または事業専従者でない</td>'
        . '      </tr>'
        . '      <tr style="height:34px;">'
        . '        <td class="text-start nowrap" style="background:#fff;">⑤　他の扶養親族、同一生計配偶者でない</td>'
        . '      </tr>'
        . '      <tr style="height:34px;">'
        . '        <td class="text-start nowrap" style="background:#fff;">⑥　年末の年齢が16歳以上</td>'
        . '        <td style="background:#fff;">38万円</td>'
        . '      </tr>'
        . '      <tr style="height:34px;">'
        . '        <td class="text-start nowrap" style="background:#fff;">⑦　年末の年齢が19歳以上23歳未満</td>'
        . '        <td style="background:#fff;">63万円</td>'
        . '      </tr>'
        . '      <tr style="height:34px;">'
        . '        <td class="text-start nowrap" style="background:#fff;">⑧　年末の年齢が70歳以上</td>'
        . '        <td style="background:#fff;">48万円</td>'
        . '      </tr>'
        . '      <tr style="height:34px;">'
        . '        <td class="text-start nowrap" style="background:#fff;">⑨　納税者または配偶者の直系尊属で同居</td>'
        . '        <td style="background:#fff;">58万円</td>'
        . '      </tr>'
        . '    </tbody>'
        . '  </table>'

        . '</div>'
        . '<div class="help-text" style="padding-left:2em; text-indent:-1em;">※同居老親等とは、納税者本人または配偶者の直系尊属（父母、祖父母まで）で同居を常としている人（老人ホームなどに入所している人は該当しない）のことです。</div>',
],    

'tokutei_shinzoku_tokubetsu' => [
    'title' => '特定親族特別控除',
    'html'  => ''
        . '<div class="help-text">　納税者に<span style="color:#701616;">特定親族</span>（★）がいる場合には、特定親族特別控除として一定の金額を所得金額から控除できます（令和７年分以降）。</div>'

        . '<div class="help-text" style="padding-left:2.5em; text-indent:-2.5em; margin-bottom:4px;">★<span style="color:#701616;">特定親族</span></div>'
        . '<div class="help-text" style="padding-left:2.5em; margin-bottom:4px;">その年の12月31日の現況で、次の全ての要件に当てはまる人をいう。</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">①年齢が19歳以上23歳未満であること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">②配偶者以外の親族（6親等内の血族および3親等内の姻族）であること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">③納税者と生計を一にしていること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">④合計所得金額が58万円超123万円以下（給与収入で123万円超188万円以下）であること</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em; line-height:1.25; margin-bottom:0;">⑤青色申告者の青色事業専従者または白色申告者の事業専従者でないこと</div>'
        . '<div class="help-text" style="padding-left:4.0em; text-indent:-1.5em;">⑥他の人の同一生計配偶者や扶養親族となっていないこと</div>'

        . '<div class="ms-3 mb-1"><strong>○扶養控除と特定親族特別控除の関係</strong></div>'
        . '<table class="help-tax-table mx-auto" style="width:660px;">'
        . '  <thead>'
        . '    <tr>'
        . '      <th rowspan="2" style="width:90px;background:#e9eff7;">年齢</th>'
        . '      <th colspan="3" rowspan="2" style="width:120px;background:#e9eff7;">親族区分</th>'
        . '      <th rowspan="2" style="width:150px;background:#e9eff7;">扶養控除額<br>（合計所得金額≦58万円）</th>'
        . '      <th colspan="3" style="background:#e9eff7;">特定親族特別控除</th>'
        . '    </tr>'
        . '    <tr>'
        . '      <th colspan="2" style="background:#F7F9FB;">（58万円＜合計所得金額≦123万円）</th>'
        . '      <th style="background:#F7F9FB;">控除額</th>'
        . '    </tr>'
        . '  </thead>'
        . '  <tbody>'
        . '    <tr>'
        . '      <td class="text-start nowrap" style="background:#F7F9FB;">16歳未満</td>'
        . '      <td colspan="3" class="text-center nowrap" style="background:#F7F9FB;">年少扶養親族</td>'
        . '      <td colspan="4" class="text-center nowrap th-cream">（対象外）</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start nowrap" style="background:#F7F9FB;">16歳以上<br>19歳未満</td>'
        . '      <td colspan="3" class="text-center nowrap" style="background:#F7F9FB;">控除対象扶養親族</td>'
        . '      <td class="text-center nowrap">38万円</td>'
        . '      <td colspan="3" class="text-center nowrap th-cream">（対象外）</td>'
        . '    </tr>'

        . '    <tr>'
        . '      <td rowspan="9" class="text-start nowrap" style="background:#F7F9FB;">19歳以上<br>23歳未満</td>'
        . '      <td colspan="3" rowspan="9" class="text-center" style="background:#F7F9FB; white-space:normal; line-height:1.25;">特定扶養親族<br>（特定親族）</td>'
        . '      <td rowspan="9" class="text-center nowrap">63万円</td>'
        . '      <td class="text-start ps-5 nowrap b-r-no" style="width:100px;">58万円超</td>'
        . '      <td class="text-end pe-5 nowrap b-l-no" style="width:100px;">85万円以下</td>'
        . '      <td class="text-center nowrap" style="width:100px;">63万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start ps-5 nowrap b-r-no">85万円超</td>'
        . '      <td class="text-end pe-5 nowrap b-l-no">90万円以下</td>'
        . '      <td class="text-center nowrap">61万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start ps-5 nowrap b-r-no">90万円超</td>'
        . '      <td class="text-end pe-5 nowrap b-l-no">95万円以下</td>'
        . '      <td class="text-center nowrap">51万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start ps-5 nowrap b-r-no">95万円超</td>'
        . '      <td class="text-end pe-5 nowrap b-l-no">100万円以下</td>'
        . '      <td class="text-center nowrap">41万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start ps-5 nowrap b-r-no">100万円超</td>'
        . '      <td class="text-end pe-5 nowrap b-l-no">105万円以下</td>'
        . '      <td class="text-center nowrap">31万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start ps-5 nowrap b-r-no">105万円超</td>'
        . '      <td class="text-end pe-5 nowrap b-l-no">110万円以下</td>'
        . '      <td class="text-center nowrap">21万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start ps-5 nowrap b-r-no">110万円超</td>'
        . '      <td class="text-end pe-5 nowrap b-l-no">115万円以下</td>'
        . '      <td class="text-center nowrap">11万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start ps-5 nowrap b-r-no">115万円超</td>'
        . '      <td class="text-end pe-5 nowrap b-l-no">120万円以下</td>'
        . '      <td class="text-center nowrap">6万円</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="text-start ps-5 nowrap b-r-no">120万円超</td>'
        . '      <td class="text-end pe-5 nowrap b-l-no">123万円以下</td>'
        . '      <td class="text-center nowrap">3万円</td>'
        . '    </tr>'

        . '    <tr>'
        . '      <td class="text-start nowrap" style="background:#F7F9FB;">23歳以上<br>70歳未満</td>'
        . '      <td colspan="3" class="text-center nowrap" style="background:#F7F9FB;">控除対象扶養親族</td>'
        . '      <td class="text-center nowrap">38万円</td>'
        . '      <td colspan="3" class="text-center nowrap th-cream">（対象外）</td>'
        . '    </tr>'

        . '    <tr>'
        . '      <td rowspan="2" class="text-start nowrap" style="background:#F7F9FB;">70歳以上</td>'
        . '      <td colspan="3" class="text-center nowrap b-b-no" style="background:#F7F9FB;">老人扶養親族</td>'
        . '      <td class="text-center nowrap">48万円</td>'
        . '      <td colspan="3" rowspan="2" class="text-center nowrap th-cream">（対象外）</td>'
        . '    </tr>'
        . '    <tr>'
        . '      <td class="b-t-no" style="width:34px;background:#F7F9FB;"></td>'
        . '      <td colspan="2" class="text-center nowrap" style="background:#F7F9FB;">同居老親等</td>'
        . '      <td class="text-center nowrap">58万円</td>'
        . '    </tr>'
        . '  </tbody>'
        . '</table>',
],    
    
];