<?php

namespace App\Http\Requests;

use App\Domain\Tax\DTO\FurusatoInput;
use Illuminate\Foundation\Http\FormRequest;

final class FurusatoInputRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        $integerRange = ['integer', 'min:0', 'max:1000000000'];

        return [
            'data_id' => ['nullable', 'integer'],
            'w17' => ['required', ...$integerRange],
            'w18' => ['required', ...$integerRange],
            'ab6' => ['required', ...$integerRange],
            'ab56' => ['required', 'integer', 'min:1', 'max:1000000000'],
            'v6' => ['nullable', 'integer', 'in:0,1,2'],
            'w6' => ['nullable', 'integer', 'in:0,1,2'],
            'x6' => ['nullable', 'integer', 'in:0,1,2'],
            'household_composition' => ['nullable', ...$integerRange],
            'spouse_status' => ['nullable', ...$integerRange],
            'spouse_income_class' => ['nullable', ...$integerRange],
            'taxpayer_age_category' => ['nullable', ...$integerRange],
            'spouse_age_category' => ['nullable', ...$integerRange],
            'num_dependents' => ['nullable', ...$integerRange],
            'num_minor_dependents' => ['nullable', ...$integerRange],
            'num_elder_dependents' => ['nullable', ...$integerRange],
            'num_special_dependents' => ['nullable', ...$integerRange],
            'num_disabled_dependents' => ['nullable', ...$integerRange],
            'prefecture_code' => ['nullable', ...$integerRange],
            'municipality_code' => ['nullable', ...$integerRange],
            'residence_type' => ['nullable', ...$integerRange],
            'is_special_collection' => ['nullable', 'boolean'],
            'is_blue_return' => ['nullable', 'boolean'],
            'is_new_resident' => ['nullable', 'boolean'],
            'salary_income' => ['nullable', ...$integerRange],
            'bonus_income' => ['nullable', ...$integerRange],
            'business_income' => ['nullable', ...$integerRange],
            'real_estate_income' => ['nullable', ...$integerRange],
            'pension_income' => ['nullable', ...$integerRange],
            'dividend_income' => ['nullable', ...$integerRange],
            'interest_income' => ['nullable', ...$integerRange],
            'capital_gain_income' => ['nullable', ...$integerRange],
            'temporary_income' => ['nullable', ...$integerRange],
            'other_income' => ['nullable', ...$integerRange],
            'social_insurance_premium' => ['nullable', ...$integerRange],
            'life_insurance_premium' => ['nullable', ...$integerRange],
            'earthquake_insurance_premium' => ['nullable', ...$integerRange],
            'medical_expense_deduction' => ['nullable', ...$integerRange],
            'small_enterprise_mutual_aid' => ['nullable', ...$integerRange],
            'spouse_deduction_amount' => ['nullable', ...$integerRange],
            'special_spouse_deduction_amount' => ['nullable', ...$integerRange],
            'dependent_deduction_amount' => ['nullable', ...$integerRange],
            'disability_deduction_amount' => ['nullable', ...$integerRange],
            'widow_widower_deduction_amount' => ['nullable', ...$integerRange],
            'single_parent_deduction_amount' => ['nullable', ...$integerRange],
            'working_student_deduction_amount' => ['nullable', ...$integerRange],
            'basic_deduction_amount' => ['nullable', ...$integerRange],
            'donation_deduction_amount' => ['nullable', ...$integerRange],
            'housing_loan_deduction_amount' => ['nullable', ...$integerRange],
            'furusato_donation_total' => ['nullable', ...$integerRange],
            'other_donation_total' => ['nullable', ...$integerRange],
            'prefectural_income_tax_rate' => ['nullable', 'numeric', 'min:0', 'max:1'],
            'municipal_income_tax_rate' => ['nullable', 'numeric', 'min:0', 'max:1'],
            'prefectural_equal_share' => ['nullable', ...$integerRange],
            'municipal_equal_share' => ['nullable', ...$integerRange],
            'taxation_method' => ['nullable', ...$integerRange],
            'notes' => ['nullable', 'string', 'max:1000'],
            'q2' => ['nullable', 'numeric', 'min:0', 'max:1'],
            'q3' => ['nullable', 'numeric', 'min:0', 'max:1'],
            'q4' => ['nullable', 'numeric', 'min:0', 'max:1'],
            'q5' => ['nullable', 'numeric', 'min:0', 'max:1'],
        ];
    }

    public function toDto(): FurusatoInput
    {
        return new FurusatoInput(
            w17: (int) $this->input('w17'),
            w18: (int) $this->input('w18'),
            ab6: (int) $this->input('ab6'),
            ab56: max(1, (int) $this->input('ab56')),
            v6: (int) $this->input('v6', 0),
            w6: (int) $this->input('w6', 0),
            x6: (int) $this->input('x6', 0),
            householdComposition: (int) $this->input('household_composition', 0),
            spouseStatus: (int) $this->input('spouse_status', 0),
            spouseIncomeClass: (int) $this->input('spouse_income_class', 0),
            taxpayerAgeCategory: (int) $this->input('taxpayer_age_category', 0),
            spouseAgeCategory: (int) $this->input('spouse_age_category', 0),
            numDependents: (int) $this->input('num_dependents', 0),
            numMinorDependents: (int) $this->input('num_minor_dependents', 0),
            numElderDependents: (int) $this->input('num_elder_dependents', 0),
            numSpecialDependents: (int) $this->input('num_special_dependents', 0),
            numDisabledDependents: (int) $this->input('num_disabled_dependents', 0),
            prefectureCode: (int) $this->input('prefecture_code', 0),
            municipalityCode: (int) $this->input('municipality_code', 0),
            residenceType: (int) $this->input('residence_type', 0),
            isSpecialCollection: $this->boolean('is_special_collection'),
            isBlueReturn: $this->boolean('is_blue_return'),
            isNewResident: $this->boolean('is_new_resident'),
            salaryIncome: (int) $this->input('salary_income', 0),
            bonusIncome: (int) $this->input('bonus_income', 0),
            businessIncome: (int) $this->input('business_income', 0),
            realEstateIncome: (int) $this->input('real_estate_income', 0),
            pensionIncome: (int) $this->input('pension_income', 0),
            dividendIncome: (int) $this->input('dividend_income', 0),
            interestIncome: (int) $this->input('interest_income', 0),
            capitalGainIncome: (int) $this->input('capital_gain_income', 0),
            temporaryIncome: (int) $this->input('temporary_income', 0),
            otherIncome: (int) $this->input('other_income', 0),
            socialInsurancePremium: (int) $this->input('social_insurance_premium', 0),
            lifeInsurancePremium: (int) $this->input('life_insurance_premium', 0),
            earthquakeInsurancePremium: (int) $this->input('earthquake_insurance_premium', 0),
            medicalExpenseDeduction: (int) $this->input('medical_expense_deduction', 0),
            smallEnterpriseMutualAid: (int) $this->input('small_enterprise_mutual_aid', 0),
            spouseDeductionAmount: (int) $this->input('spouse_deduction_amount', 0),
            specialSpouseDeductionAmount: (int) $this->input('special_spouse_deduction_amount', 0),
            dependentDeductionAmount: (int) $this->input('dependent_deduction_amount', 0),
            disabilityDeductionAmount: (int) $this->input('disability_deduction_amount', 0),
            widowWidowerDeductionAmount: (int) $this->input('widow_widower_deduction_amount', 0),
            singleParentDeductionAmount: (int) $this->input('single_parent_deduction_amount', 0),
            workingStudentDeductionAmount: (int) $this->input('working_student_deduction_amount', 0),
            basicDeductionAmount: (int) $this->input('basic_deduction_amount', 0),
            donationDeductionAmount: (int) $this->input('donation_deduction_amount', 0),
            housingLoanDeductionAmount: (int) $this->input('housing_loan_deduction_amount', 0),
            furusatoDonationTotal: (int) $this->input('furusato_donation_total', 0),
            otherDonationTotal: (int) $this->input('other_donation_total', 0),
            prefecturalIncomeTaxRate: (float) $this->input('prefectural_income_tax_rate', 0.0),
            municipalIncomeTaxRate: (float) $this->input('municipal_income_tax_rate', 0.0),
            prefecturalEqualShare: (int) $this->input('prefectural_equal_share', 0),
            municipalEqualShare: (int) $this->input('municipal_equal_share', 0),
            taxationMethod: (int) $this->input('taxation_method', 0),
            notes: (string) $this->input('notes', ''),
            q2: (float) $this->input('q2', 0.0),
            q3: (float) $this->input('q3', 0.0),
            q4: (float) $this->input('q4', 0.0),
            q5: (float) $this->input('q5', 0.0),
        );
    }
}