<?php
namespace App\Domain\Tax\DTO;

final class FurusatoInput
{
    public function __construct(
        public int $w17,
        public int $w18,
        public int $ab6,
        public int $ab56,
        public int $v6 = 0,
        public int $w6 = 0,
        public int $x6 = 0,
        public int $household_composition = 0,
        public int $spouse_status = 0,
        public int $spouse_income_class = 0,
        public int $taxpayer_age_category = 0,
        public int $spouse_age_category = 0,
        public int $num_dependents = 0,
        public int $num_minor_dependents = 0,
        public int $num_elder_dependents = 0,
        public int $num_special_dependents = 0,
        public int $num_disabled_dependents = 0,
        public int $prefecture_code = 0,
        public int $municipality_code = 0,
        public int $residence_type = 0,
        public int $special_collection_flag = 0,
        public int $blue_return_flag = 0,
        public int $new_resident_flag = 0,
        public int $salary_income = 0,
        public int $bonus_income = 0,
        public int $business_income = 0,
        public int $real_estate_income = 0,
        public int $pension_income = 0,
        public int $dividend_income = 0,
        public int $interest_income = 0,
        public int $capital_gain_income = 0,
        public int $temporary_income = 0,
        public int $other_income = 0,
        public int $social_insurance_premium = 0,
        public int $life_insurance_premium = 0,
        public int $earthquake_insurance_premium = 0,
        public int $medical_expense_deduction = 0,
        public int $small_enterprise_mutual_aid = 0,
        public int $spouse_deduction_amount = 0,
        public int $special_spouse_deduction_amount = 0,
        public int $dependent_deduction_amount = 0,
        public int $disability_deduction_amount = 0,
        public int $widow_widower_deduction_amount = 0,
        public int $single_parent_deduction_amount = 0,
        public int $working_student_deduction_amount = 0,
        public int $basic_deduction_amount = 0,
        public int $donation_deduction_amount = 0,
        public int $housing_loan_deduction_amount = 0,
        public float $prefectural_income_tax_rate = 0.0,
        public float $municipal_income_tax_rate = 0.0,
        public int $prefectural_equal_share = 0,
        public int $municipal_equal_share = 0,
        public int $taxation_method = 0,
        public string $notes = '',
        public float $q2 = 0.0,
        public float $q3 = 0.0,
        public float $q4 = 0.0,
        public float $q5 = 0.0,
    ) {}
}